import time
def logo():
    print("  ████████████████████████████████████  __.--~~.,-.__     ")
    time.sleep(0.1)
    print("  █    ██ ██ ██   ██    ██    ██  █  █  `~-._.-(`-.__`-.  ")
    time.sleep(0.1)
    print("  █ ██ ██ ██ ██ ████ ██ ██ ██ ███   ██           \    `~~` ")
    time.sleep(0.1)
    print("  █ █████    ██   ██    ██    ████ ███      .--./ \       ")
    time.sleep(0.1)
    print("  █ ██ ██ ██ ██ ████ █ ███ █ █████ ███     /#   \  \.--.  ")
    time.sleep(0.1)
    print("  █    ██ ██ ██   ██ ██ ██ ██ ████ ███     \    /  /#   \ ")
    time.sleep(0.1)
    print("  ████████████████████████████████████      '--'   \    / ")
    time.sleep(0.1)
    print(" ███████████████████████████████████████            '--'  ")
    time.sleep(0.1)
    print(" █    █    ██    ██    █    █ ████    ██")
    time.sleep(0.1)
    print(" █ ██ █ ██ ██ ██ ██ ████ ██ █ ████ █████")
    time.sleep(0.1)
    print(" █ ████ ██ ██ ██ ██    █ ██ █ ████    ██")
    time.sleep(0.1)
    print(" █ ██ █ ██ ██ ██ █████ █ ██ █ ████ █████")
    time.sleep(0.1)
    print(" █    █    ██ ██ ██    █    █    █    ██")
    time.sleep(0.1)
    print(" ███████████████████████████████████████")
    time.sleep(0.3)
    print(' Powered by Sp0ge and MaBoi')
    print(' https://github.com/Sp0ge/CherryConsole')


    time.sleep(1)